name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Change to correct directory
        run: cd testgithub

      - name: Install dependencies
        run: npm install
        working-directory: testgithub

      - name: Run tests
        run: npm test
        working-directory: testgithub
