name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
       
      - name: set up maven
        uses: s4u/maven-install-action@v1.0.0
        with:
          maven-version: '3.9.5'
          maven-opts: '-Xmx1024m -XX:MaxPermSize=512m -XX:+UseCompressedOops -XX:+UseParallelGC -XX:+UseStringDeduplication'
          maven-home: ${{ github.workspace }}/maven
          cache: true
          cache-path: ${{ github.workspace }}/.m2
          cache-key: maven-${{ hashFiles('**/pom.xml') }}
          cache-version: 1.0.0
      - name: Build with Maven
        run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -s ${{ github.workspace }}/maven/settings.xml
      - name: Run tests with Maven
        run: mvn test -Dmaven.javadoc.skip=true -B -V -s ${{ github.workspace }}/maven/settings.xml
      

  
      
